### ISSUE TITLE
Motif Scaffolding and Binder Design?

### ISSUE THREAD

**Issue by Amelie-Schreiber** [microsoft/protein-frame-flow#16]
Will there be functionality and examples added for functional motif scaffolding and binder design?

**Comment by jasonkyuyim** [comment]
Hi, we recently put out a pre-print for motif-scaffolding. We're currently working on updating the repo with code. Sorry for the wait!
https://arxiv.org/abs/2401.04082

**Comment by amelie-iska** [comment]
Any updates on when the motif scaffolding functionality will be available?

**Comment by jasonkyuyim** [comment]
Sorry, other priorities have come up that pushed down the motif-scaffolding functionality. It is still on my todo... A rough estimate I can give is sometime in late March.

**Comment by Kirito-Ausna** [comment]
Hello, thank you for your awesome work and open sources. I am currently trying to scaffold some motifs for research purposes. Would you like to update on the motif scaffolding functionality for help? RFDiff is a bit heavy for my experiment amount. I will appreciate it if you can give me some guidances.

**Comment by jasonkyuyim** [comment]
The paper was recently accepted at TMLR so I have worked on the code release.
