### ISSUE TITLE
Error when running on my own processed data

### ISSUE THREAD

**Issue by zaixizhang** [microsoft/protein-frame-flow#21]
Hi,
Thanks for the brilliant work! I tried to use data/process_pdb_files.py to process my own data for training. However, I encounter the following error:
![85d836ddc3b759624da21d8d8347942](https://github.com/microsoft/protein-frame-flow/assets/52197241/d2100f64-46cb-4731-b11c-ec526da17e3c)

**Comment by jasonkyuyim** [comment]
Why is DataLoader being called? `process_pdb_files.py` shouldn't be using pytorch's dataloader at all.
