### ISSUE TITLE
About the motif guidance implementation

### ISSUE THREAD

**Issue by Kirito-Ausna** [microsoft/protein-frame-flow#22]
Hi! Thanks for your awesome work!
I noticed that you will calculate the following:
![image](https://github.com/microsoft/protein-frame-flow/assets/60833761/5337b311-5e09-4580-98a0-8edefa83cd51)
I am a little confused about calculating the SO(3) norm. And the IPA module includes the torch.linalg.eigh() operation, which is known to be highly unstable when back-propagating. I am concerned that the gradient in the motif guidance will contain a lot of NaNs and be meaningless. I am very curious about how I can resolve this issue.
Could you kindly give me some guidance?

Thanks a lot!

**Comment by Kirito-Ausna** [comment]
Hi Jason! Thanks for your response! Could you please tell me how to calculate the SO(3) norm and its weights? Since the paper didn't contain enough details to reproduce. Or could you share your schedule to release the official codes? Thanks a lot!

**Comment by jasonkyuyim** [comment]
This has been added. (Sorry for the delay. The paper was accepted this week at TMLR.) https://github.com/microsoft/protein-frame-flow/blob/motif_scaffolding/data/interpolant.py#L327
